
delete billentity_base from billentity_base inner join bill_base on billentity_base.iBillId=bill_base.id where bill_base.cBillNo='pc_attachmentgroup'  and bill_base.tenant_id=0 ;
delete billtemplate_base from billtemplate_base inner join bill_base on billtemplate_base.iBillId=bill_base.id where bill_base.cBillNo='pc_attachmentgroup'  and bill_base.tenant_id=0 ;
delete billtplgroup_base from billtplgroup_base inner join bill_base on billtplgroup_base.iBillId=bill_base.id where bill_base.cBillNo='pc_attachmentgroup'  and bill_base.tenant_id=0 ;
delete billitem_base from billitem_base inner JOIN bill_base on billitem_base.iBillId=bill_base.id where bill_base.cBillNo='pc_attachmentgroup'  and bill_base.tenant_id=0 ;
delete from pub_makebillrule_detail where makebill_id in (select makebill_id from pub_makebillrule where iBillId in (select id from bill_base where cBillNo='pc_attachmentgroup' and tenant_id=0 ));
delete from pub_makebillrule where iBillId in (select id from bill_base where cBillNo='pc_attachmentgroup' and tenant_id=0 );
delete from bill_base where cBillNo='pc_attachmentgroup' and tenant_id=0 ;

select ifnull(max(id),0)+1 into @id4 from bill_base;
insert into bill_base(`id`,`cBillNo`,`cName`,`cCardKey`,`cSubId`,`iDefTplId`,`iDefPrnTplId`,`iOrder`,`bAllowMultiTpl`,`cDefWhere`,`isDeleted`,`bPrintLimited`,`iSystem`,`cAuthId`,`cBillType`,`cBeanId`,`cFilterId`,`bRowAuthControl`,`bColumnAuthControl`,`bRowAuthObject`,`bColumnAuthControlled`,`bRowAuthControlled`,`cPersonDataSource`,`cCarry`,`authGroupKey`,`tenant_id`) values (@id4,'pc_attachmentgroup','附件分组卡片','pc_attachmentgroup','PC',null,null,0,0,null,0,null,1,null,'Archive',null,null,0,0,0,0,0,null,null,'pc_attachmentgroup',0);

select ifnull(max(id),0)+1 into @id9 from billentity_base;
insert into billentity_base(`id`,`iBillId`,`cCode`,`cName`,`cSubId`,`iOrder`,`isDeleted`,`cDataSourceName`,`cPrimaryKey`,`iSystem`,`bMain`,`cForeignKey`,`cParentCode`,`childrenField`,`cModelType`,`bIsNull`,`tenant_id`) values (@id9,@id4,'pc_attachmentgroupcard','附件分组实体','PC',null,0,'pc.attachment.AttachmentGroup','id',1,1,null,null,null,null,null,0);

select ifnull(max(id),0)+1 into @id14 from billtemplate_base;
insert into billtemplate_base(`id`,`iBillId`,`cName`,`iOrder`,`iTplMode`,`iWidth`,`isDeleted`,`cPrintSetting`,`cPageHeader`,`cPageFooter`,`cTitleHeight`,`iPrintTotal`,`iFixedCols`,`cMemo`,`cTitle`,`iGridStyle`,`cRowLayout`,`cTitleStyle`,`cTotalColor`,`cAmongColor`,`cFixedColor`,`templateType`,`tenant_id`) values (@id14,@id4,'附件分组显示模板',0,2,'600',0,null,null,null,null,null,null,null,'附件分组',null,null,null,null,null,null,'modal',0);

select ifnull(max(id),0)+1 into @id20 from billtplgroup_base;
insert into billtplgroup_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`cCode`,`cName`,`cSubId`,`iOrder`,`cDataSourceName`,`cPrimaryKey`,`isDeleted`,`iSystem`,`bMain`,`cForeignKey`,`cParentDataSource`,`cType`,`iParentID`,`cAlign`,`iCols`,`cStyle`,`cImage`,`tenant_id`) values (@id20,@id4,@id9,@id14,'body','数据体','PC','11','pc.attachment.AttachmentGroup','id',0,1,1,null,null,'div',null,'top',1,'{"classname":"padd-bottom-60"}',null,0);

select ifnull(max(id),0)+1 into @id25 from billitem_base;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id25,@id4,@id9,@id14,@id20,'PC','billType','billType','单据类型','单据类型',1,'255',1,1,null,0,1,0,null,null,null,null,null,null,null,null,0,null,'100',null,'100',null,1,0,1,null,0,'false',null,null,null,1,1,0,0,0,'pc.attachment.AttachmentGroup',null,null,'Select','pc_attachmentGroupBillType',null,0,null,null,null,0,0,0);
set @id26=@id25+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id26,@id4,@id9,@id14,@id20,'PC','code','code','分组编码','分组编码',2,'255',1,0,null,0,1,0,null,null,null,null,null,null,null,null,1,null,null,null,'100',null,null,null,1,null,1,null,null,null,0,1,null,null,null,null,'pc.attachment.AttachmentGroup',null,null,'Input',null,null,0,null,null,null,0,0,0);
set @id27=@id26+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id27,@id4,@id9,@id14,@id20,'PC','name','name','分组名称','分组名称',3,'255',1,0,null,0,1,0,null,null,null,null,null,null,null,null,1,null,null,null,'150',null,null,null,1,null,1,null,null,null,1,1,null,1,null,null,'pc.attachment.AttachmentGroup',null,null,'Input',null,null,0,null,null,null,0,0,0);
set @id28=@id27+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id28,@id4,@id9,@id14,@id20,'PC','stopstatus','stopstatus','启用状态','启用状态',4,'255',1,1,null,0,1,0,null,null,null,null,null,0,0,null,1,null,'100',null,'100',null,1,0,1,null,0,'false',null,null,null,1,1,0,0,0,'pc.attachment.AttachmentGroup',null,null,'Radio','aa_stopstatus',null,0,null,null,null,0,0,0);
set @id29=@id28+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id29,@id4,@id9,@id14,@id20,'PC','description','description','说明','说明',5,'255',1,0,null,0,0,0,null,null,null,null,null,null,null,null,1,null,null,null,'150',null,null,null,1,null,1,null,null,null,1,1,null,1,null,null,'pc.attachment.AttachmentGroup',null,null,'Input',null,null,0,null,'{"type":"textarea"}',null,0,0,0);
set @id30=@id29+1;
insert into billitem_base(`id`,`iBillId`,`iBillEntityId`,`iTplId`,`iBillTplGroupId`,`cSubId`,`cFieldName`,`cName`,`cCaption`,`cShowCaption`,`iOrder`,`iMaxLength`,`iFieldType`,`bEnum`,`cEnumString`,`isDeleted`,`bMustSelect`,`bHidden`,`cRefType`,`cRefId`,`cRefRetID`,`cDataRule`,`iFunctionType`,`bSplit`,`bExtend`,`iNumPoint`,`bCanModify`,`cSourceType`,`iMaxShowLen`,`cMemo`,`iColWidth`,`cSumType`,`iAlign`,`bNeedSum`,`bShowIt`,`bFixed`,`bFilter`,`cDefaultValue`,`cFormatData`,`cUserId`,`iTabIndex`,`bIsNull`,`bPrintCaption`,`bJointQuery`,`bPrintUpCase`,`bSelfDefine`,`cDataSourceName`,`cOrder`,`bCheck`,`cControlType`,`cEnumType`,`refReturn`,`bShowInRowAuth`,`iRowAuthBillId`,`cStyle`,`cSelfDefineType`,`bVmExclude`,`bRowAuthDim`,`tenant_id`) values (@id30,@id4,@id9,@id14,@id20,'PC','id','id','附件分组id','附件分组id',8,'255',1,0,null,0,1,1,null,null,null,null,null,0,0,null,1,null,'255',null,1,null,1,0,1,null,0,null,null,null,'11',1,1,0,0,0,'pc.attachment.AttachmentGroup',null,null,'Input',null,null,0,null,null,0,0,0,0);









select ifnull(max(id),0)+1 into @id73 from bill_command;
insert into bill_command(`id`,`name`,`action`,`billnumber`,`target`,`ruleid`,`svcurl`,`httpmethod`,`subid`,`system`,`parameter`,`authid`,`tenant_id`) values (@id73,'cmdSave','save','pc_attachmentgroup','footertoolbar',null,'/bill/save','POST','PC',1,null,null,0);
set @id74=@id73+1;
insert into bill_command(`id`,`name`,`action`,`billnumber`,`target`,`ruleid`,`svcurl`,`httpmethod`,`subid`,`system`,`parameter`,`authid`,`tenant_id`) values (@id74,'cmdEdit','Edit','pc_attachmentgroup','Browstoolbar',null,'/bill/edit','GET','PC',1,null,'aa_paystartbaselistedit',0);
set @id75=@id74+1;
insert into bill_command(`id`,`name`,`action`,`billnumber`,`target`,`ruleid`,`svcurl`,`httpmethod`,`subid`,`system`,`parameter`,`authid`,`tenant_id`) values (@id75,'cmdDelete','delete','pc_attachmentgroup','Browstoolbar',null,'/bill/delete','POST','PC',1,null,'aa_paystartbaselistbatchdelete',0);

update bill_base set `iDefTplId`=@id14 where `id`=@id4;
update pub_ref set cFilterId=@id45 where cbillnum = 'pc_attachmentgroup';